# Increase replicas for high availability
#replicaCount: 1

service:
  type: ClusterIP
  port: 80
  httpsPort: 443
  httpsTargetPort: https
  # prometheus metrics. Can probably be removed.
  metricsPort: 9117
  # externalTrafficPolicy retains original IP address so that we can limit based on src IP
  externalTrafficPolicy: Local
  annotations: {}

healthcheckHttps: false

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
 
livenessProbeHeaders:
- name: X-Forwarded-Proto
  value: https
readinessProbeHeaders:
- name: X-Forwarded-Proto
  value: https

ingress:
  enabled: true
  certManager: true
  hostname: my.disciple.tools
  annotations: 
  - kubernetes.io/ingress.class: nginx
  # necessary to install disciple tools theme
  - nginx.ingress.kubernetes.io/proxy-body-size: 8m
  # limits access to an IP / CIDR range
  - nginx.ingress.kubernetes.io/whitelist-source-range: 1.2.3.4/32
  # This host entry is needed inaddition to hostname above and tls entry below
  hosts:
  - name: my.disciple.tools
    path: /
  tls:
  - hosts:
      - my.disciple.tools
    secretName: my.disciple.tools-tls

# create using k create configmap custom-htaccess --from-file wordpress-htaccess.conf
# if you specify a different filename the key will be incorrect!
allowOverrideNone: true
customHTAccessCM: custom-htaccess
