# Increase replicas for high availability
#replicaCount: 1

service:
  type: ClusterIP
  port: 80
  httpsPort: 443
  httpsTargetPort: https
  # externalTrafficPolicy retains original IP address so that we can limit based on src IP
  externalTrafficPolicy: Local
  annotations: {}

healthcheckHttps: false

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
 
livenessProbeHeaders:
- name: X-Forwarded-Proto
  value: https
readinessProbeHeaders:
- name: X-Forwarded-Proto
  value: https

ingress:
  enabled: true
  certManager: true
  hostname: dt.example.com
  annotations: 
  # necessary to install disciple tools theme
   nginx.ingress.kubernetes.io/proxy-body-size: "8m"
  # limits access to an IP / CIDR range
   nginx.ingress.kubernetes.io/whitelist-source-range: "8.1.1.2/32,8.4.3.8/27"
  # tells the ingress to use cluster issuer "letsencrypt-prod"
   cert-manager.io/cluster-issuer: "letsencrypt-prod"

  # This host entry is needed inaddition to hostname above and tls entry below
  hosts:
  - name: dt.example.com
    path: /
  tls:
  - hosts:
      - dt.example.com
    secretName: dt.example.com-tls

# create using k create configmap custom-htaccess --from-file wordpress-htaccess.conf
# if you specify a different filename the key will be incorrect!
allowOverrideNone: true
customHTAccessCM: custom-htaccess
